### ISSUE TITLE
Supporting automatic width and height like EmbedVideo 2.X did

### ISSUE THREAD

**Issue by D3nnis3n** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#26] opened 2022-06-26 19:27 UTC
Hello,
EmbedVideo 2.0 supported the following:
`<youtube alignment="center" width="100%" height="auto">ud_refZuQoA</youtube>`
(or: {{#ev:youtube|id=ud_refZuQoA|alignment=center|width=100%|height=auto}})

This automatically centered the video and sized it fittingly to maximum width of its container, keeping a height that made sense for aspect ratio - unfortunately I have not found an equivalent that works in your cool updated version, hence putting this as feature request. Using the same ways in EmbedVideo 3.0 will lead to a extremely small video that ignores it is supposed to extend to full width and adjust its height.

![image](https://user-images.githubusercontent.com/25908592/175830523-5d88d51e-137d-48d3-a150-221bde063318.png)

Unfortunatley I can no longer use the older EmbedVideo, as it broke with some Update, throwing a Error: invalid magic word 'evt'.

For now I have manually set width to 1200, which unfortunately leads to weird height aspect ratios when using different sized screens, as width doesn't variably adjust.

![image](https://user-images.githubusercontent.com/25908592/175830768-81f6e886-c0d4-458e-af6c-f424554101c9.png)

^ This view it did via the instructions mentioned at the start by default, adjusting perfectly on mobile or changing the screen.

**Comment by octfx** [comment] 2022-06-26 19:31
I'll look into it! :)

**Comment by D3nnis3n** [comment] 2022-06-26 19:32
Hey,
that was a bit extremely fast response, I was still editing things.

Here you go:
https://wiki.play.eco/en/

**Comment by octfx** [comment] 2022-06-26 20:19
So, I've checked the code and found the following:  
Setting the width to `100%` results in EmbedVideo setting the width to `$wgEmbedVideoDefaultWidth`.  
The check for `is_numeric` evaluates to false (this code part is taken verbatim from the original extension)
https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/2f0a657c120b658a1c45e43c7202527294050cf1/includes/EmbedService/AbstractEmbedService.php#L211

Since EmbedVideo v3, the global default width is changed to `320` from `640`.  
My first idea would be to try setting `$wgEmbedVideoDefaultWidth = 640;` and see if this helps.

But I'll check further if something is not working as intended!

**Comment by D3nnis3n** [comment] 2022-06-26 20:28
I think the more interesting part is height="auto" - the width seems to be the expected 320, but height is not adjusting to fit.

I don't really know what's different, but width="100%" did actually lead to the container with being used and height="auto" made a good aspect ratio out of it. V3 just seems to default to the default width and probably a default height as well, as it does not try to make a viewable aspect ratio out of it. Weird. Not sure what magic V2 had hidden.

**Comment by octfx** [comment] 2022-07-02 09:18
I can't fully re-create your issue on a local mediawiki installation.  

Would you be able to create a test page on your wiki with the config mentioned in the first post?  
(I've tried to create a page myself, but VE throws a captcha error for anonymous users)

**Comment by D3nnis3n** [comment] 2022-07-05 10:12
Hey,
I'll be setting up such a page as soon as I get to it.

The captcha issue is indeed pretty problematic, but seems to be a MediaWiki bug. Unfortunately we can't turn it off, as that led to massive spam roll before: https://phabricator.wikimedia.org/T311449

**Comment by D3nnis3n** [comment] 2022-07-11 12:45
Hey,
sorry it took so long, I added a test page here:
https://wiki.play.eco/de/EmbedVideoTest

If you want I can temporarily remove the captcha for you. We are currently hoping for a fix of the captcha, as without it we get around a hundred automated spam pages a day. Once I get time I'll probably disable the editing for unregistered people until a fix is available, but I need to get some minutes to get myself familiar with the configuration for that again.

**Comment by D3nnis3n** [comment] 2022-07-25 08:36
Have you been able to find anything new?

**Comment by octfx** [comment] 2022-08-04 17:30
Sorry for the late reply! I'm somewhat time constrained atm.😕

This seems to be an issue with the auto resizer:
https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/master/resources/ext.embedVideo.js#L34

The problem is that I cant replicate the error using a local environment. I'll try to look at this in the following days, but if some other kind soul wants to take this on, I'd be more than happy!

**Comment by octfx** [comment] 2023-01-27 16:15
@D3nnis3n this should be fixed in the upcoming release :)

**Comment by alistair3149** [comment] 2023-01-27 18:24
In 3.2.0, you can use `|autoresize=true` to enable automatic sizing :) Closing the issue now.

**Closed by alistair3149** 2023-01-27 18:24 UTC
Labels: enhancement, help wanted

**Comment by D3nnis3n** [comment] 2024-03-26 13:00
Just saw this, thanks a lot!

Is there any way to use that in combination with a maximum height / width? Using autoresize=true seems to prevent width=640px to work?
